# Generated by Django 4.2.7 on 2025-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last read at'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, verbose_name='unread count'),
        ),
    ]
