# Generated by Django 4.2.7 on 2025-03-03 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='productivity_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='productivity score'),
        ),
        migrations.AddField(
            model_name='timereport',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('table', 'Table')], default='bar', max_length=10, verbose_name='chart type'),
        ),
        migrations.AddField(
            model_name='timereport',
            name='report_format',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='custom', max_length=10, verbose_name='report format'),
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('total_hours', models.FloatField(default=0, verbose_name='total hours')),
                ('billable_hours', models.FloatField(default=0, verbose_name='billable hours')),
                ('break_time', models.FloatField(default=0, verbose_name='break time')),
                ('productivity_score', models.FloatField(default=0, verbose_name='productivity score')),
                ('task_completion_rate', models.FloatField(default=0, verbose_name='task completion rate')),
                ('tasks_worked', models.IntegerField(default=0, verbose_name='tasks worked')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='tasks completed')),
                ('hourly_data', models.JSONField(blank=True, default=dict, verbose_name='hourly data')),
                ('task_data', models.JSONField(blank=True, default=dict, verbose_name='task data')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily analytics',
                'verbose_name_plural': 'daily analytics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'business')},
            },
        ),
    ]
