# Generated by Django 4.2.7 on 2025-03-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_fiscalyear_is_current_fiscalyear_is_locked'),
        ('time_management', '0003_timeentry_productivity_score_timereport_chart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='clients.fiscalyear'),
        ),
    ]
