# Generated by Django 4.2.7 on 2025-03-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_priority_model'),
        ('tasks', 'delete_unused_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='templatechildtask',
            name='priority',
        ),
        migrations.DeleteModel(
            name='TaskPriority',
        ),
    ]
