# Generated by Django 4.2.7 on 2025-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_remove_priority_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_value',
            field=models.PositiveIntegerField(blank=True, default=50, help_text='優先度値（1〜100、数値が小さいほど優先度が高い）', null=True, verbose_name='priority value'),
        ),
    ]
