# Generated by Django 4.2.7 on 2025-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='yearly_day',
            field=models.IntegerField(blank=True, help_text='毎年の特定の日に実行する場合に設定（例：1日）', null=True, verbose_name='day for yearly recurrence'),
        ),
        migrations.AddField(
            model_name='task',
            name='yearly_month',
            field=models.IntegerField(blank=True, help_text='毎年の特定の月に実行する場合に設定（例：4月）', null=True, verbose_name='month for yearly recurrence'),
        ),
    ]
