# Generated by Django 4.2.7 on 2025-03-04 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_fiscal_year_task_is_fiscal_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_tasks', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks', to=settings.AUTH_USER_MODEL, verbose_name='worker'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='assignee_type',
            field=models.CharField(choices=[('worker', '作業者'), ('reviewer', 'レビュー担当者'), ('none', 'なし')], default='worker', help_text='このステータスで担当となるユーザータイプ', max_length=20, verbose_name='assignee type'),
        ),
    ]
