# Generated by Django 4.2.7 on 2025-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_yearly_day_task_yearly_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='assignee_type',
            field=models.CharField(choices=[('worker', '作業者'), ('reviewer', 'レビュー担当者'), ('approver', '承認者'), ('none', 'なし')], default='worker', help_text='このステータスで担当となるユーザータイプ', max_length=20, verbose_name='assignee type'),
        ),
    ]
