# Generated by Django 4.2.7 on 2025-03-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('tasks', '0004_task_reviewer_task_worker_taskstatus_assignee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='business.workspace'),
        ),
    ]
