# Generated by Django 4.2.7 on 2025-03-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_archived_at_task_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_archived',
        ),
    ]
