# Generated by Django 4.2.7 on 2025-03-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_last_generated_date_task_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'ordering': ['priority_value', 'name'], 'verbose_name': 'task priority', 'verbose_name_plural': 'task priorities'},
        ),
        migrations.RemoveField(
            model_name='taskpriority',
            name='level',
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='priority_value',
            field=models.PositiveIntegerField(default=50, verbose_name='priority value'),
        ),
    ]
