# Generated by Django 4.2.7 on 2025-03-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskpriority_options_remove_taskpriority_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpriority',
            name='priority_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='priority value'),
        ),
    ]
