# Generated by Django 4.2.7 on 2025-03-08 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskpriority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'task comment', 'verbose_name_plural': 'task comments'},
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskcomment'),
        ),
    ]
