# Generated by Django 4.2.7 on 2025-03-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskcomment_options_taskattachment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='html content'),
        ),
    ]
