# Generated by Django 4.2.7 on 2025-03-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('tasks', '0011_taskcomment_html_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('schedule_type', models.CharField(choices=[('monthly_start', '月初作成・当月締め切り'), ('monthly_end', '月末作成・翌月締め切り'), ('fiscal_relative', '決算日基準'), ('custom', 'カスタム設定')], default='monthly_start', max_length=30, verbose_name='schedule type')),
                ('recurrence', models.CharField(choices=[('once', '一度のみ'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('quarterly', '四半期ごと'), ('yearly', '毎年'), ('with_parent', '親テンプレートと同時')], default='monthly', max_length=20, verbose_name='recurrence')),
                ('creation_day', models.IntegerField(blank=True, null=True, verbose_name='creation day')),
                ('deadline_day', models.IntegerField(blank=True, null=True, verbose_name='deadline day')),
                ('deadline_next_month', models.BooleanField(default=False, verbose_name='deadline next month')),
                ('fiscal_date_reference', models.CharField(choices=[('start_date', '開始日'), ('end_date', '終了日')], default='end_date', max_length=20, verbose_name='fiscal date reference')),
                ('reference_date_type', models.CharField(choices=[('execution_date', '実行日（バッチ処理実行日）'), ('fiscal_start', '決算期開始日'), ('fiscal_end', '決算期終了日'), ('month_start', '当月初日'), ('month_end', '当月末日'), ('parent_creation', '親タスク作成日')], default='execution_date', max_length=30, verbose_name='reference date type')),
                ('creation_date_offset', models.IntegerField(default=0, verbose_name='creation date offset')),
                ('deadline_date_offset', models.IntegerField(default=5, verbose_name='deadline date offset')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_schedules', to='business.business')),
            ],
            options={
                'verbose_name': 'task schedule',
                'verbose_name_plural': 'task schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateChildTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='estimated hours')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('has_custom_schedule', models.BooleanField(default=False, verbose_name='has custom schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_child_tasks', to='business.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_child_tasks', to='tasks.taskcategory')),
                ('parent_template', models.ForeignKey(limit_choices_to={'is_template': True}, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='tasks.task')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_child_tasks', to='tasks.taskpriority')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_child_tasks', to='tasks.taskschedule')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_child_tasks', to='tasks.taskstatus')),
            ],
            options={
                'verbose_name': 'template child task',
                'verbose_name_plural': 'template child tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
