# Generated by Django 4.2.7 on 2025-03-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_taskpriority_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weekday',
            field=models.IntegerField(blank=True, null=True, verbose_name='weekday for weekly recurrence'),
        ),
    ]
