# Generated by Django 4.2.7 on 2025-03-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='business_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='business day of month for monthly recurrence'),
        ),
        migrations.AddField(
            model_name='task',
            name='monthday',
            field=models.IntegerField(blank=True, null=True, verbose_name='day of month for monthly recurrence'),
        ),
    ]
