# Generated by Django 4.2.7 on 2025-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_business_day_task_monthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='consider_holidays',
            field=models.BooleanField(default=True, help_text='営業日計算時に祝日を考慮するかどうか（Trueの場合、土日と祝日をスキップ）', verbose_name='consider holidays in business day calculation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='business_day',
            field=models.IntegerField(blank=True, help_text='毎月の特定の営業日（平日）に実行する場合に設定（例：第5営業日）', null=True, verbose_name='business day of month for monthly recurrence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='monthday',
            field=models.IntegerField(blank=True, help_text='毎月の特定の日に実行する場合に設定（例：15日）', null=True, verbose_name='day of month for monthly recurrence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weekday',
            field=models.IntegerField(blank=True, help_text='週次繰り返しの曜日指定（0=月曜日、1=火曜日、...、6=日曜日）', null=True, verbose_name='weekday for weekly recurrence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weekdays',
            field=models.CharField(blank=True, help_text='週次繰り返しの複数曜日指定（カンマ区切りの数値を保存: "0,2,4" = 月,水,金）', max_length=20, null=True, verbose_name='weekdays for weekly recurrence'),
        ),
    ]
