# Generated by Django 4.2.7 on 2025-03-02 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='business.business')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wiki_pages', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_wiki_pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.wikipage')),
            ],
            options={
                'verbose_name': 'wiki page',
                'verbose_name_plural': 'wiki pages',
                'ordering': ['parent__id', 'order', 'title'],
                'unique_together': {('business', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_page_edits', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.wikipage')),
            ],
            options={
                'verbose_name': 'wiki page version',
                'verbose_name_plural': 'wiki page versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wiki_attachments/', verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('file_type', models.CharField(max_length=100, verbose_name='file type')),
                ('file_size', models.PositiveIntegerField(verbose_name='file size')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wiki.wikipage')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wiki attachment',
                'verbose_name_plural': 'wiki attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
