# Generated by Django 4.2.7 on 2025-03-03 01:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCheckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('monthly', '月次チェック'), ('bookkeeping', '記帳代行'), ('tax_return', '税務申告書作成'), ('withholding_tax', '源泉所得税対応'), ('other', 'その他')], max_length=50, verbose_name='チェック種別')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('cycle', models.CharField(choices=[('monthly', '毎月'), ('yearly', '毎年')], default='monthly', max_length=20, verbose_name='サイクル')),
                ('create_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'client check setting',
                'verbose_name_plural': 'client check settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_period', models.PositiveIntegerField(verbose_name='期')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'fiscal year',
                'verbose_name_plural': 'fiscal years',
                'ordering': ['-fiscal_period'],
            },
        ),
        migrations.RemoveField(
            model_name='clientnote',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientnote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='client',
            name='attendance_management_software',
            field=models.CharField(blank=True, max_length=100, verbose_name='勤怠管理ソフト'),
        ),
        migrations.AddField(
            model_name='client',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='建物名・部屋番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='資本金'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='クライアントコード'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_status',
            field=models.CharField(choices=[('active', '契約中'), ('suspended', '休止中'), ('terminated', '解約'), ('preparing', '契約準備中')], default='active', max_length=20, verbose_name='契約状況'),
        ),
        migrations.AddField(
            model_name='client',
            name='corporate_individual',
            field=models.CharField(choices=[('corporate', '法人'), ('individual', '個人')], default='corporate', max_length=20, verbose_name='法人または個人'),
        ),
        migrations.AddField(
            model_name='client',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='法人番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='設立日・開業日'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_date',
            field=models.DateField(blank=True, null=True, verbose_name='決算日'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='決算期（期）'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='client',
            name='salary_closing_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='給与締め日'),
        ),
        migrations.AddField(
            model_name='client',
            name='salary_payment_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='給与支払日'),
        ),
        migrations.AddField(
            model_name='client',
            name='salary_payment_month',
            field=models.CharField(blank=True, choices=[('current', '当月'), ('next', '翌月')], default='next', max_length=10, verbose_name='給与支払月'),
        ),
        migrations.AddField(
            model_name='client',
            name='some_task_flag',
            field=models.BooleanField(default=False, verbose_name='タスク設定フラグ'),
        ),
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_eLTAX_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='eLTAX ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_eTax_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='eTax ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_invoice_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='インボイスNo'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_invoice_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='インボイス登録日'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_taxpayer_confirmation_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='納税者確認番号'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.DeleteModel(
            name='ClientContract',
        ),
        migrations.DeleteModel(
            name='ClientNote',
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientchecksetting',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_settings', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientchecksetting',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_check_settings', to='tasks.task'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='account_manager',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_position',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fiscal_year_end',
        ),
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='website',
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('client', 'fiscal_period')},
        ),
        migrations.AlterUniqueTogether(
            name='clientchecksetting',
            unique_together={('client', 'check_type')},
        ),
    ]
