# Generated by Django 4.2.7 on 2025-03-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('clients', '0003_clientchecksetting_fiscalyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='クライアントコード'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('business', 'name')},
        ),
    ]
