# Generated by Django 4.2.7 on 2025-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='現在の期'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='ロック'),
        ),
    ]
