# Generated by Django 4.2.7 on 2025-03-08 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_taskcomment_html_content'),
        ('clients', '0005_fiscalyear_is_current_fiscalyear_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='some_task_flag',
        ),
        migrations.AddField(
            model_name='client',
            name='task_template_type',
            field=models.CharField(choices=[('default', 'デフォルトテンプレートを使用'), ('custom', 'カスタマイズしたテンプレートを使用'), ('none', 'テンプレートを使用しない（手動作成のみ）')], default='default', max_length=20, verbose_name='使用するテンプレートタイプ'),
        ),
        migrations.AddField(
            model_name='client',
            name='task_template_usage',
            field=models.CharField(choices=[('enabled', 'テンプレート使用する'), ('disabled', 'テンプレート使用しない')], default='enabled', max_length=20, verbose_name='タスクテンプレート使用設定'),
        ),
        migrations.CreateModel(
            name='ClientTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('deadline_type', models.CharField(choices=[('business_days', '営業日'), ('calendar_days', 'カレンダー日付'), ('fiscal_date', '決算日基準')], default='calendar_days', max_length=20, verbose_name='期限タイプ')),
                ('deadline_value', models.IntegerField(default=0, help_text='営業日/カレンダー日の場合は日数、決算日基準の場合は±日数', verbose_name='期限値')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='見積工数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_templates', to='tasks.taskcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='clients.client')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_templates', to='tasks.taskpriority')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_template_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='レビュー担当者')),
                ('template', models.ForeignKey(help_text='Reference to the original template task', on_delete=django.db.models.deletion.CASCADE, related_name='client_templates', to='tasks.task')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_template_worker', to=settings.AUTH_USER_MODEL, verbose_name='作業担当者')),
            ],
            options={
                'verbose_name': 'client task template',
                'verbose_name_plural': 'client task templates',
                'ordering': ['order', 'title'],
                'unique_together': {('client', 'template')},
            },
        ),
    ]
