# Generated by Django 4.2.7 on 2025-03-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_some_task_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('income', '源泉所得税'), ('residence', '住民税')], max_length=20, verbose_name='税種別')),
                ('rule_type', models.CharField(choices=[('principle', '原則'), ('exception', '特例')], max_length=20, verbose_name='ルール種別')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rule_histories', to='clients.client')),
            ],
            options={
                'verbose_name': '税ルール履歴',
                'verbose_name_plural': '税ルール履歴',
                'ordering': ['-start_date'],
                'unique_together': {('client', 'tax_type', 'start_date')},
            },
        ),
    ]
