# Generated by Django 4.2.7 on 2025-03-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_task_template_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientCheckSetting',
        ),
    ]
