# Generated by Django 4.2.7 on 2023-12-15 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('clients', '0009_alter_client_client_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='サービス名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_custom', models.BooleanField(default=False, verbose_name='カスタムサービス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_services', to='business.business')),
            ],
            options={
                'verbose_name': '契約サービス',
                'verbose_name_plural': '契約サービス',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '契約中'), ('suspended', '休止中'), ('terminated', '終了'), ('preparing', '準備中')], default='active', max_length=20, verbose_name='契約状態')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='報酬額')),
                ('fee_cycle', models.CharField(choices=[('monthly', '月次'), ('quarterly', '四半期'), ('yearly', '年次'), ('one_time', '一時金')], default='monthly', max_length=20, verbose_name='報酬サイクル')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('custom_service_name', models.CharField(blank=True, max_length=100, verbose_name='カスタムサービス名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to='clients.contractservice')),
            ],
            options={
                'verbose_name': 'クライアント契約',
                'verbose_name_plural': 'クライアント契約',
                'ordering': ['-start_date'],
            },
        ),
    ]
