# Generated by Django 4.2.7 on 2025-03-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_client_check_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientTaskTemplate',
        ),
    ]
