# Generated by Django 4.2.7 on 2025-03-09 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_taskcomment_html_content'),
        ('business', '0002_initial'),
        ('clients', '0010_delete_clienttasktemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スケジュール名')),
                ('schedule_type', models.CharField(choices=[('monthly_start', '月初作成・当月締め切り'), ('monthly_end', '月末作成・翌月締め切り'), ('fiscal_relative', '決算日基準'), ('custom', 'カスタム設定')], max_length=20, verbose_name='スケジュールタイプ')),
                ('creation_day', models.IntegerField(blank=True, null=True, verbose_name='タスク作成日')),
                ('deadline_day', models.IntegerField(blank=True, null=True, verbose_name='タスク期限日')),
                ('fiscal_date_reference', models.CharField(blank=True, choices=[('start_date', '開始日基準'), ('end_date', '終了日基準')], max_length=20, null=True, verbose_name='決算日参照タイプ')),
                ('deadline_next_month', models.BooleanField(default=False, verbose_name='期限日を翌月に設定')),
                ('recurrence', models.CharField(choices=[('monthly', '毎月'), ('quarterly', '四半期ごと'), ('yearly', '毎年'), ('once', '一度のみ')], default='monthly', max_length=20, verbose_name='繰り返し')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_template_schedules', to='business.business')),
            ],
            options={
                'verbose_name': 'task template schedule',
                'verbose_name_plural': 'task template schedules',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClientTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='見積工数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='最終タスク生成日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_templates', to='tasks.taskcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='clients.client')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_templates', to='tasks.taskpriority')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_template_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='レビュー担当者')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='clients.tasktemplateschedule')),
                ('template_task', models.ForeignKey(help_text='Reference to the original template task', on_delete=django.db.models.deletion.CASCADE, related_name='client_templates', to='tasks.task')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_template_worker', to=settings.AUTH_USER_MODEL, verbose_name='作業担当者')),
            ],
            options={
                'verbose_name': 'client task template',
                'verbose_name_plural': 'client task templates',
                'ordering': ['order', 'title'],
                'unique_together': {('client', 'template_task')},
            },
        ),
    ]
