# Generated by Django 4.2.7 on 2023-12-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_contractservice_clientcontract'),
        ('clients', '0011_tasktemplateschedule_clienttasktemplate'),
    ]

    operations = [
    ] 