# Generated by Django 4.2.7 on 2025-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_priority_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Webサイト'),
        ),
    ]
