# Generated by Django 4.2.7 on 2025-03-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='task_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
