# Generated by Django 4.2.7 on 2025-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_task_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='saved_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
