# Generated by Django 4.2.7 on 2025-03-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences_saved_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_task_filter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='saved_task_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
